### ISSUE TITLE
Man, why Anne name week is goin like thiz ;-;?

### ISSUE THREAD

**Issue by FridayNightSans** [RecoloredPoyo4/PoyoEngine#4]
![Screenshot_20210606-190530](https://user-images.githubusercontent.com/81144896/120923835-d275ef00-c6fa-11eb-8ce7-3ef6b9780a65.png)
Expain me? Why u use like thiz ;-;

**Comment by RecoloredPoyo4** [comment]
Is not really a bug. But eh, closing
