### ISSUE TITLE
Downscroll broke

### ISSUE THREAD

**Issue by DabKnight** [RecoloredPoyo4/PoyoEngine#5]
https://user-images.githubusercontent.com/82740118/120924736-add44400-c707-11eb-9eeb-c8c48f42984e.mp4

a

**Comment by Jered-plays** [comment]
Broke

**Comment by FridayNightSans** [comment]
That not broke
He named Downsrcoll but it actually it is Memory Chart mode. Lmao

**Comment by Jered-plays** [comment]
Yes

**Comment by RecoloredPoyo4** [comment]
I didn't break it Lucky did. I will transfer this over to a new version when Lucky fixes it. closed

**Comment by FridayNightSans** [comment]
> I didn't break it Lucky did. I will transfer this over to a new version when Lucky fixes it. closed

luckydog,
